# Generated by Django 6.0.1 on 2026-01-31 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_permission_remove_accessrule_element_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Permission',
            new_name='AppPermission',
        ),
    ]
